apiVersion: v1
kind: Pod
metadata:
  name: client2
  namespace: portfolio1
  labels:
    app: client2
spec:
  containers:
    - name: client2
      image: samarkansal/portfolio:client2.0
      stdin: true
      tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: client2
  namespace: portfolio1
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: client2
  type: LoadBalancer
