apiVersion: v1
kind: Pod
metadata:
  name: client3
  namespace: portfolio1
  labels:
    app: client3
spec:
  containers:
    - name: client3
      image: samarkansal/portfolio:client3.0
      stdin: true
      tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: client3
  namespace: portfolio1
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: client3
  type: LoadBalancer
